# Generated by Django 5.1.4 on 2025-01-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_categories_id_datas_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
