# Generated by Django 5.1.4 on 2025-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_aboutus_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(),
        ),
    ]
