# Generated by Django 5.1.4 on 2025-01-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_datas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='img_url',
            field=models.ImageField(max_length=200, upload_to='posts/images'),
        ),
    ]
