# Generated by Django 5.1.4 on 2025-01-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categories_datas_categories_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='categories_id',
            new_name='categories',
        ),
    ]
