# Generated by Django 5.1.4 on 2025-01-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='img_url',
        ),
    ]
