# Generated by Django 5.1.4 on 2025-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_datas_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
